version: '3.8'

services:
  backend:
    build: .
    container_name: icinema_backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/icinemadb
    volumes:
      - .:/app
  
  frontend:
    build: ./frontend
    container_name: icinema_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo
    container_name: icinema_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
